export interface TimezoneOption {
	label: string;
	value: string;
}

export const TIMEZONES: TimezoneOption[] = [
	// Southeast Asia - Priority region
	{ label: "Asia/Jakarta (WIB)", value: "Asia/Jakarta" },
	{ label: "Asia/Pontianak (WIB)", value: "Asia/Pontianak" },
	{ label: "Asia/Makassar (WITA)", value: "Asia/Makassar" },
	{ label: "Asia/Jayapura (WIT)", value: "Asia/Jayapura" },
	{ label: "Asia/Bangkok (ICT)", value: "Asia/Bangkok" },
	{ label: "Asia/Phnom_Penh (ICT)", value: "Asia/Phnom_Penh" },
	{ label: "Asia/Vientiane (ICT)", value: "Asia/Vientiane" },
	{ label: "Asia/Ho_Chi_Minh (ICT)", value: "Asia/Ho_Chi_Minh" },
	{ label: "Asia/Manila (PST)", value: "Asia/Manila" },
	{ label: "Asia/Kuala_Lumpur (MYT)", value: "Asia/Kuala_Lumpur" },
	{ label: "Asia/Kuching (MYT)", value: "Asia/Kuching" },
	{ label: "Asia/Singapore (SGT)", value: "Asia/Singapore" },
	{ label: "Asia/Yangon (MMT)", value: "Asia/Yangon" },
	{ label: "Asia/Dili (TLT)", value: "Asia/Dili" },

	// Other Asian timezones
	{ label: "Asia/Dubai (GST)", value: "Asia/Dubai" },
	{ label: "Asia/Karachi (PKT)", value: "Asia/Karachi" },
	{ label: "Asia/Kolkata (IST)", value: "Asia/Kolkata" },
	{ label: "Asia/Kathmandu (NPT)", value: "Asia/Kathmandu" },
	{ label: "Asia/Colombo (LKST)", value: "Asia/Colombo" },
	{ label: "Asia/Dhaka (BDT)", value: "Asia/Dhaka" },
	{ label: "Asia/Almaty (ALMT)", value: "Asia/Almaty" },
	{ label: "Asia/Bishkek (KGT)", value: "Asia/Bishkek" },
	{ label: "Asia/Yekaterinburg (YEKT)", value: "Asia/Yekaterinburg" },
	{ label: "Asia/Omsk (OMST)", value: "Asia/Omsk" },
	{ label: "Asia/Krasnoyarsk (KRAT)", value: "Asia/Krasnoyarsk" },
	{ label: "Asia/Irkutsk (IRKT)", value: "Asia/Irkutsk" },
	{ label: "Asia/Yakutsk (YAKT)", value: "Asia/Yakutsk" },
	{ label: "Asia/Vladivostok (VLAT)", value: "Asia/Vladivostok" },
	{ label: "Asia/Kamchatka (PETT)", value: "Asia/Kamchatka" },
	{ label: "Asia/Anadyr (ANAT)", value: "Asia/Anadyr" },
	{ label: "Asia/Shanghai (CST)", value: "Asia/Shanghai" },
	{ label: "Asia/Hong_Kong (HKT)", value: "Asia/Hong_Kong" },
	{ label: "Asia/Taipei (CST)", value: "Asia/Taipei" },
	{ label: "Asia/Macau (CST)", value: "Asia/Macau" },
	{ label: "Asia/Seoul (KST)", value: "Asia/Seoul" },
	{ label: "Asia/Tokyo (JST)", value: "Asia/Tokyo" },
	{ label: "Asia/Pyongyang (KST)", value: "Asia/Pyongyang" },
	{ label: "Asia/Ulaanbaatar (ULAT)", value: "Asia/Ulaanbaatar" },
	{ label: "Asia/Hovd (HOVT)", value: "Asia/Hovd" },
	{ label: "Asia/Choibalsan (CHOT)", value: "Asia/Choibalsan" },

	// Australia and Oceania
	{ label: "Australia/Perth (AWST)", value: "Australia/Perth" },
	{ label: "Australia/Eucla (AWCWST)", value: "Australia/Eucla" },
	{ label: "Australia/Darwin (ACST)", value: "Australia/Darwin" },
	{ label: "Australia/Adelaide (ACDT)", value: "Australia/Adelaide" },
	{ label: "Australia/Broken_Hill (ACDT)", value: "Australia/Broken_Hill" },
	{ label: "Australia/Melbourne (AEDT)", value: "Australia/Melbourne" },
	{ label: "Australia/Sydney (AEDT)", value: "Australia/Sydney" },
	{ label: "Australia/Lord_Howe (LHST)", value: "Australia/Lord_Howe" },
	{ label: "Pacific/Bougainville (BST)", value: "Pacific/Bougainville" },
	{ label: "Pacific/Port_Moresby (PGT)", value: "Pacific/Port_Moresby" },
	{ label: "Pacific/Bismarck (BST)", value: "Pacific/Bismarck" },
	{ label: "Pacific/Guadalcanal (SBT)", value: "Pacific/Guadalcanal" },
	{ label: "Pacific/Vanuatu (VUT)", value: "Pacific/Vanuatu" },
	{ label: "Pacific/Fiji (FJT)", value: "Pacific/Fiji" },
	{ label: "Pacific/Tongatapu (TOT)", value: "Pacific/Tongatapu" },
	{ label: "Pacific/Kiritimati (LINT)", value: "Pacific/Kiritimati" },
	{ label: "Pacific/Nauru (NRT)", value: "Pacific/Nauru" },
	{ label: "Pacific/Palau (PWT)", value: "Pacific/Palau" },
	{ label: "Pacific/Chuuk (CHUT)", value: "Pacific/Chuuk" },
	{ label: "Pacific/Pohnpei (PONT)", value: "Pacific/Pohnpei" },
	{ label: "Pacific/Kosrae (KOST)", value: "Pacific/Kosrae" },
	{ label: "Pacific/Majuro (MHT)", value: "Pacific/Majuro" },
	{ label: "Pacific/Kwajalein (MHT)", value: "Pacific/Kwajalein" },
	{ label: "Pacific/Auckland (NZDT)", value: "Pacific/Auckland" },
	{ label: "Pacific/Chatham (CHADT)", value: "Pacific/Chatham" },
	{ label: "Pacific/Fakaofo (TKT)", value: "Pacific/Fakaofo" },
	{ label: "Pacific/Apia (WST)", value: "Pacific/Apia" },
	{ label: "Pacific/Enderbury (PHOT)", value: "Pacific/Enderbury" },
	{ label: "Pacific/Tahiti (TAHT)", value: "Pacific/Tahiti" },
	{ label: "Pacific/Marquesas (MART)", value: "Pacific/Marquesas" },
	{ label: "Pacific/Honolulu (HST)", value: "Pacific/Honolulu" },

	// Europe
	{ label: "Europe/London (GMT/BST)", value: "Europe/London" },
	{ label: "Europe/Dublin (GMT/IST)", value: "Europe/Dublin" },
	{ label: "Europe/Lisbon (WEST/WET)", value: "Europe/Lisbon" },
	{ label: "Europe/Madrid (CET)", value: "Europe/Madrid" },
	{ label: "Europe/Paris (CET)", value: "Europe/Paris" },
	{ label: "Europe/Berlin (CET)", value: "Europe/Berlin" },
	{ label: "Europe/Rome (CET)", value: "Europe/Rome" },
	{ label: "Europe/Amsterdam (CET)", value: "Europe/Amsterdam" },
	{ label: "Europe/Brussels (CET)", value: "Europe/Brussels" },
	{ label: "Europe/Vienna (CET)", value: "Europe/Vienna" },
	{ label: "Europe/Zurich (CET)", value: "Europe/Zurich" },
	{ label: "Europe/Prague (CET)", value: "Europe/Prague" },
	{ label: "Europe/Budapest (CET)", value: "Europe/Budapest" },
	{ label: "Europe/Warsaw (CET)", value: "Europe/Warsaw" },
	{ label: "Europe/Copenhagen (CET)", value: "Europe/Copenhagen" },
	{ label: "Europe/Oslo (CET)", value: "Europe/Oslo" },
	{ label: "Europe/Stockholm (CET)", value: "Europe/Stockholm" },
	{ label: "Europe/Helsinki (EET)", value: "Europe/Helsinki" },
	{ label: "Europe/Athens (EET)", value: "Europe/Athens" },
	{ label: "Europe/Bucharest (EET)", value: "Europe/Bucharest" },
	{ label: "Europe/Sofia (EET)", value: "Europe/Sofia" },
	{ label: "Europe/Belgrade (CET)", value: "Europe/Belgrade" },
	{ label: "Europe/Zagreb (CET)", value: "Europe/Zagreb" },
	{ label: "Europe/Sarajevo (CET)", value: "Europe/Sarajevo" },
	{ label: "Europe/Skopje (CET)", value: "Europe/Skopje" },
	{ label: "Europe/Tallinn (EET)", value: "Europe/Tallinn" },
	{ label: "Europe/Riga (EET)", value: "Europe/Riga" },
	{ label: "Europe/Vilnius (EET)", value: "Europe/Vilnius" },
	{ label: "Europe/Moscow (MSK)", value: "Europe/Moscow" },
	{ label: "Europe/Kiev (EET)", value: "Europe/Kiev" },
	{ label: "Europe/Chisinau (EET)", value: "Europe/Chisinau" },
	{ label: "Atlantic/Canary (WEST)", value: "Atlantic/Canary" },
	{ label: "Atlantic/Azores (AZOT)", value: "Atlantic/Azores" },
	{ label: "Atlantic/Madeira (WEST)", value: "Atlantic/Madeira" },

	// Americas
	{ label: "America/New_York (EST/EDT)", value: "America/New_York" },
	{ label: "America/Chicago (CST/CDT)", value: "America/Chicago" },
	{ label: "America/Denver (MST/MDT)", value: "America/Denver" },
	{ label: "America/Los_Angeles (PST/PDT)", value: "America/Los_Angeles" },
	{ label: "America/Anchorage (AKST/AKDT)", value: "America/Anchorage" },
	{ label: "Pacific/Honolulu (HST)", value: "Pacific/Honolulu" },
	{ label: "America/Toronto (EST/EDT)", value: "America/Toronto" },
	{ label: "America/Halifax (AST/ADT)", value: "America/Halifax" },
	{ label: "America/St_Johns (NST/NDT)", value: "America/St_Johns" },
	{ label: "America/Mexico_City (CST)", value: "America/Mexico_City" },
	{ label: "America/Cancun (EST)", value: "America/Cancun" },
	{ label: "America/Merida (CST)", value: "America/Merida" },
	{ label: "America/Mazatlan (MST)", value: "America/Mazatlan" },
	{ label: "America/Chihuahua (MST)", value: "America/Chihuahua" },
	{ label: "America/Tijuana (PST)", value: "America/Tijuana" },
	{ label: "America/Bogota (COT)", value: "America/Bogota" },
	{ label: "America/Lima (PET)", value: "America/Lima" },
	{ label: "America/La_Paz (BOT)", value: "America/La_Paz" },
	{ label: "America/Caracas (VET)", value: "America/Caracas" },
	{ label: "America/Santiago (CLST)", value: "America/Santiago" },
	{ label: "America/Argentina/Buenos_Aires (ART)", value: "America/Argentina/Buenos_Aires" },
	{ label: "America/Sao_Paulo (BRT)", value: "America/Sao_Paulo" },
	{ label: "America/Montevideo (UYT)", value: "America/Montevideo" },
	{ label: "America/Paramaribo (SRT)", value: "America/Paramaribo" },
	{ label: "America/Cayenne (GFT)", value: "America/Cayenne" },
	{ label: "America/Guyana (GYT)", value: "America/Guyana" },

	// Africa
	{ label: "Africa/Cairo (EET)", value: "Africa/Cairo" },
	{ label: "Africa/Johannesburg (SAST)", value: "Africa/Johannesburg" },
	{ label: "Africa/Lagos (WAT)", value: "Africa/Lagos" },
	{ label: "Africa/Nairobi (EAT)", value: "Africa/Nairobi" },
	{ label: "Africa/Casablanca (WEST)", value: "Africa/Casablanca" },
	{ label: "Africa/Algiers (CET)", value: "Africa/Algiers" },
	{ label: "Africa/Accra (GMT)", value: "Africa/Accra" },
	{ label: "Africa/Addis_Ababa (EAT)", value: "Africa/Addis_Ababa" },
	{ label: "Africa/Khartoum (CAT)", value: "Africa/Khartoum" },
	{ label: "Africa/Dar_es_Salaam (EAT)", value: "Africa/Dar_es_Salaam" },
	{ label: "Africa/Kampala (EAT)", value: "Africa/Kampala" },
	{ label: "Africa/Mogadishu (EAT)", value: "Africa/Mogadishu" },
	{ label: "Africa/Maputo (CAT)", value: "Africa/Maputo" },
	{ label: "Africa/Antananarivo (EAT)", value: "Africa/Antananarivo" },
	{ label: "Africa/Windhoek (CAT)", value: "Africa/Windhoek" },
	{ label: "Africa/Gaborone (CAT)", value: "Africa/Gaborone" },
	{ label: "Africa/Maseru (SAST)", value: "Africa/Maseru" },
	{ label: "Africa/Mbabane (SAST)", value: "Africa/Mbabane" },
	{ label: "Africa/Kigali (CAT)", value: "Africa/Kigali" },
	{ label: "Africa/Bujumbura (CAT)", value: "Africa/Bujumbura" },
	{ label: "Africa/Kinshasa (WAT)", value: "Africa/Kinshasa" },
	{ label: "Africa/Lubumbashi (CAT)", value: "Africa/Lubumbashi" },
	{ label: "Africa/Harare (CAT)", value: "Africa/Harare" },
	{ label: "Africa/Lusaka (CAT)", value: "Africa/Lusaka" },
	{ label: "Africa/Ouagadougou (GMT)", value: "Africa/Ouagadougou" },
	{ label: "Africa/Bamako (GMT)", value: "Africa/Bamako" },
	{ label: "Africa/Niamey (WAT)", value: "Africa/Niamey" },
	{ label: "Africa/Ndjamena (WAT)", value: "Africa/Ndjamena" },
	{ label: "Africa/Dakar (GMT)", value: "Africa/Dakar" },
	{ label: "Africa/Bissau (GMT)", value: "Africa/Bissau" },
	{ label: "Africa/Conakry (GMT)", value: "Africa/Conakry" },
	{ label: "Africa/Monrovia (GMT)", value: "Africa/Monrovia" },
	{ label: "Africa/Freetown (GMT)", value: "Africa/Freetown" },
	{ label: "Africa/Abidjan (GMT)", value: "Africa/Abidjan" },
	{ label: "Africa/Djibouti (EAT)", value: "Africa/Djibouti" },
	{ label: "Africa/Asmara (EAT)", value: "Africa/Asmara" },
	{ label: "Indian/Mayotte (EAT)", value: "Indian/Mayotte" },
	{ label: "Indian/Comoro (EAT)", value: "Indian/Comoro" },
	{ label: "Indian/Mauritius (MUT)", value: "Indian/Mauritius" },
	{ label: "Indian/Reunion (RET)", value: "Indian/Reunion" },
	{ label: "Indian/Maldives (MVT)", value: "Indian/Maldives" },
	{ label: "Indian/Kerguelen (TFT)", value: "Indian/Kerguelen" },
	{ label: "Indian/Mahe (SCT)", value: "Indian/Mahe" },
	{ label: "Indian/Chagos (IOT)", value: "Indian/Chagos" },

	// Arctic
	{ label: "Arctic/Longyearbyen (CET)", value: "Arctic/Longyearbyen" },

	// Antarctica
	{ label: "Antarctica/Casey (AWST)", value: "Antarctica/Casey" },
	{ label: "Antarctica/Davis (DAVT)", value: "Antarctica/Davis" },
	{ label: "Antarctica/DumontDUrville (DDUT)", value: "Antarctica/DumontDUrville" },
	{ label: "Antarctica/Mawson (MAWT)", value: "Antarctica/Mawson" },
	{ label: "Antarctica/McMurdo (NZDT)", value: "Antarctica/McMurdo" },
	{ label: "Antarctica/Palmer (CLST)", value: "Antarctica/Palmer" },
	{ label: "Antarctica/Rothera (ART)", value: "Antarctica/Rothera" },
	{ label: "Antarctica/Syowa (EAT)", value: "Antarctica/Syowa" },
	{ label: "Antarctica/Troll (CET)", value: "Antarctica/Troll" },
	{ label: "Antarctica/Vostok (VOST)", value: "Antarctica/Vostok" },
];

// Helper function to find timezone by value
export function getTimezoneByValue(value: string): TimezoneOption | undefined {
	return TIMEZONES.find((tz) => tz.value === value);
}