export const MENTOR_REGISTRY_ABI = [
	{
		inputs: [],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		inputs: [],
		name: "ADDRESS_UPDATE_TYPEHASH",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MENTOR_REGISTER_TYPEHASH",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "eip712Domain",
		outputs: [
			{ internalType: "bytes1", name: "fields", type: "bytes1" },
			{ internalType: "string", name: "name", type: "string" },
			{ internalType: "string", name: "version", type: "string" },
			{ internalType: "uint256", name: "chainId", type: "uint256" },
			{ internalType: "address", name: "verifyingContract", type: "address" },
			{ internalType: "bytes32", name: "salt", type: "bytes32" },
			{ internalType: "uint256[]", name: "extensions", type: "uint256[]" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "_username", type: "string" }],
		name: "getMentor",
		outputs: [
			{ internalType: "string", name: "username", type: "string" },
			{ internalType: "address", name: "currentAddress", type: "address" },
			{ internalType: "bool", name: "exists", type: "bool" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_mentorAddress", type: "address" },
		],
		name: "getMentorByAddress",
		outputs: [
			{ internalType: "string", name: "username", type: "string" },
			{ internalType: "address", name: "mentorAddr", type: "address" },
			{ internalType: "bool", name: "exists", type: "bool" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "_user", type: "address" }],
		name: "getNonce",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address[]", name: "addresses", type: "address[]" },
		],
		name: "getNonces",
		outputs: [
			{ internalType: "uint256[]", name: "noncesArray", type: "uint256[]" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "", type: "address" }],
		name: "mentorAddressToUsername",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "", type: "string" }],
		name: "mentors",
		outputs: [
			{ internalType: "string", name: "username", type: "string" },
			{ internalType: "address", name: "currentAddress", type: "address" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "", type: "address" }],
		name: "nonces",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_username", type: "string" },
			{ internalType: "address", name: "_mentorAddress", type: "address" },
		],
		name: "registerMentor",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_username", type: "string" },
			{ internalType: "address", name: "_mentorAddress", type: "address" },
			{ internalType: "uint256", name: "_deadline", type: "uint256" },
			{ internalType: "bytes", name: "signature", type: "bytes" },
		],
		name: "registerMentorByRelayer",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_username", type: "string" },
			{ internalType: "address", name: "_newAddress", type: "address" },
		],
		name: "updateAddress",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_username", type: "string" },
			{ internalType: "address", name: "_newAddress", type: "address" },
			{ internalType: "uint256", name: "_deadline", type: "uint256" },
			{ internalType: "bytes", name: "signature", type: "bytes" },
		],
		name: "updateAddressByRelayer",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "_username", type: "string" }],
		name: "usernameExists",
		outputs: [{ internalType: "bool", name: "exists", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "string",
				name: "username",
				type: "string",
			},
			{
				indexed: true,
				internalType: "address",
				name: "oldAddress",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newAddress",
				type: "address",
			},
		],
		name: "AddressUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "string",
				name: "username",
				type: "string",
			},
			{
				indexed: true,
				internalType: "address",
				name: "oldAddress",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newAddress",
				type: "address",
			},
			{
				indexed: false,
				internalType: "address",
				name: "relayer",
				type: "address",
			},
		],
		name: "AddressUpdatedByRelayer",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [],
		name: "EIP712DomainChanged",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "string",
				name: "username",
				type: "string",
			},
			{
				indexed: true,
				internalType: "address",
				name: "mentorAddress",
				type: "address",
			},
		],
		name: "MentorRegistered",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "string",
				name: "username",
				type: "string",
			},
			{
				indexed: true,
				internalType: "address",
				name: "mentorAddress",
				type: "address",
			},
			{
				indexed: false,
				internalType: "address",
				name: "relayer",
				type: "address",
			},
		],
		name: "MentorRegisteredByRelayer",
		type: "event",
	},
	{
		inputs: [],
		name: "AddressAlreadyExists",
		type: "error",
	},
	{
		inputs: [],
		name: "DeadlineExceeded",
		type: "error",
	},
	{
		inputs: [],
		name: "ECDSAInvalidSignature",
		type: "error",
	},
	{
		inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
		name: "ECDSAInvalidSignatureLength",
		type: "error",
	},
	{
		inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
		name: "ECDSAInvalidSignatureS",
		type: "error",
	},
	{
		inputs: [],
		name: "EmptyUsername",
		type: "error",
	},
	{
		inputs: [],
		name: "InvalidShortString",
		type: "error",
	},
	{
		inputs: [],
		name: "InvalidSignature",
		type: "error",
	},
	{
		inputs: [],
		name: "InvalidUsernameFormat",
		type: "error",
	},
	{
		inputs: [],
		name: "MentorDoesNotExist",
		type: "error",
	},
	{
		inputs: [{ internalType: "string", name: "str", type: "string" }],
		name: "StringTooLong",
		type: "error",
	},
	{
		inputs: [],
		name: "Unauthorized",
		type: "error",
	},
	{
		inputs: [],
		name: "UsernameAlreadyExists",
		type: "error",
	},
];
