/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorRegisteredRouteImport } from './routes/mentor.registered'
import { Route as MentorRegisterRouteImport } from './routes/mentor.register'
import { Route as MentorDashboardRouteImport } from './routes/mentor.dashboard'
import { Route as MUsernameRouteImport } from './routes/m.$username'
import { Route as MentorWalletAddressUpdateRouteImport } from './routes/mentor.$walletAddress.update'
import { Route as ApiTransactionStatusRouteImport } from './routes/api/transaction/status'
import { Route as ApiRelayerWebhookRouteImport } from './routes/api/relayer.webhook'
import { Route as ApiMentorRegisterRouteImport } from './routes/api/mentor.register'
import { Route as ApiMentorWalletAddressRouteImport } from './routes/api/mentor.$walletAddress'
import { Route as ApiMentorByUsernameUsernameRouteImport } from './routes/api/mentor-by-username.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRegisteredRoute = MentorRegisteredRouteImport.update({
  id: '/mentor/registered',
  path: '/mentor/registered',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRegisterRoute = MentorRegisterRouteImport.update({
  id: '/mentor/register',
  path: '/mentor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MUsernameRoute = MUsernameRouteImport.update({
  id: '/m/$username',
  path: '/m/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorWalletAddressUpdateRoute =
  MentorWalletAddressUpdateRouteImport.update({
    id: '/mentor/$walletAddress/update',
    path: '/mentor/$walletAddress/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransactionStatusRoute = ApiTransactionStatusRouteImport.update({
  id: '/api/transaction/status',
  path: '/api/transaction/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelayerWebhookRoute = ApiRelayerWebhookRouteImport.update({
  id: '/api/relayer/webhook',
  path: '/api/relayer/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorRegisterRoute = ApiMentorRegisterRouteImport.update({
  id: '/api/mentor/register',
  path: '/api/mentor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorWalletAddressRoute = ApiMentorWalletAddressRouteImport.update({
  id: '/api/mentor/$walletAddress',
  path: '/api/mentor/$walletAddress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorByUsernameUsernameRoute =
  ApiMentorByUsernameUsernameRouteImport.update({
    id: '/api/mentor-by-username/$username',
    path: '/api/mentor-by-username/$username',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m/$username': typeof MUsernameRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/mentor/register': typeof MentorRegisterRoute
  '/mentor/registered': typeof MentorRegisteredRoute
  '/api/mentor-by-username/$username': typeof ApiMentorByUsernameUsernameRoute
  '/api/mentor/$walletAddress': typeof ApiMentorWalletAddressRoute
  '/api/mentor/register': typeof ApiMentorRegisterRoute
  '/api/relayer/webhook': typeof ApiRelayerWebhookRoute
  '/api/transaction/status': typeof ApiTransactionStatusRoute
  '/mentor/$walletAddress/update': typeof MentorWalletAddressUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/m/$username': typeof MUsernameRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/mentor/register': typeof MentorRegisterRoute
  '/mentor/registered': typeof MentorRegisteredRoute
  '/api/mentor-by-username/$username': typeof ApiMentorByUsernameUsernameRoute
  '/api/mentor/$walletAddress': typeof ApiMentorWalletAddressRoute
  '/api/mentor/register': typeof ApiMentorRegisterRoute
  '/api/relayer/webhook': typeof ApiRelayerWebhookRoute
  '/api/transaction/status': typeof ApiTransactionStatusRoute
  '/mentor/$walletAddress/update': typeof MentorWalletAddressUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m/$username': typeof MUsernameRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/mentor/register': typeof MentorRegisterRoute
  '/mentor/registered': typeof MentorRegisteredRoute
  '/api/mentor-by-username/$username': typeof ApiMentorByUsernameUsernameRoute
  '/api/mentor/$walletAddress': typeof ApiMentorWalletAddressRoute
  '/api/mentor/register': typeof ApiMentorRegisterRoute
  '/api/relayer/webhook': typeof ApiRelayerWebhookRoute
  '/api/transaction/status': typeof ApiTransactionStatusRoute
  '/mentor/$walletAddress/update': typeof MentorWalletAddressUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m/$username'
    | '/mentor/dashboard'
    | '/mentor/register'
    | '/mentor/registered'
    | '/api/mentor-by-username/$username'
    | '/api/mentor/$walletAddress'
    | '/api/mentor/register'
    | '/api/relayer/webhook'
    | '/api/transaction/status'
    | '/mentor/$walletAddress/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/m/$username'
    | '/mentor/dashboard'
    | '/mentor/register'
    | '/mentor/registered'
    | '/api/mentor-by-username/$username'
    | '/api/mentor/$walletAddress'
    | '/api/mentor/register'
    | '/api/relayer/webhook'
    | '/api/transaction/status'
    | '/mentor/$walletAddress/update'
  id:
    | '__root__'
    | '/'
    | '/m/$username'
    | '/mentor/dashboard'
    | '/mentor/register'
    | '/mentor/registered'
    | '/api/mentor-by-username/$username'
    | '/api/mentor/$walletAddress'
    | '/api/mentor/register'
    | '/api/relayer/webhook'
    | '/api/transaction/status'
    | '/mentor/$walletAddress/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MUsernameRoute: typeof MUsernameRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  MentorRegisterRoute: typeof MentorRegisterRoute
  MentorRegisteredRoute: typeof MentorRegisteredRoute
  ApiMentorByUsernameUsernameRoute: typeof ApiMentorByUsernameUsernameRoute
  ApiMentorWalletAddressRoute: typeof ApiMentorWalletAddressRoute
  ApiMentorRegisterRoute: typeof ApiMentorRegisterRoute
  ApiRelayerWebhookRoute: typeof ApiRelayerWebhookRoute
  ApiTransactionStatusRoute: typeof ApiTransactionStatusRoute
  MentorWalletAddressUpdateRoute: typeof MentorWalletAddressUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/registered': {
      id: '/mentor/registered'
      path: '/mentor/registered'
      fullPath: '/mentor/registered'
      preLoaderRoute: typeof MentorRegisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/register': {
      id: '/mentor/register'
      path: '/mentor/register'
      fullPath: '/mentor/register'
      preLoaderRoute: typeof MentorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$username': {
      id: '/m/$username'
      path: '/m/$username'
      fullPath: '/m/$username'
      preLoaderRoute: typeof MUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/$walletAddress/update': {
      id: '/mentor/$walletAddress/update'
      path: '/mentor/$walletAddress/update'
      fullPath: '/mentor/$walletAddress/update'
      preLoaderRoute: typeof MentorWalletAddressUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transaction/status': {
      id: '/api/transaction/status'
      path: '/api/transaction/status'
      fullPath: '/api/transaction/status'
      preLoaderRoute: typeof ApiTransactionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relayer/webhook': {
      id: '/api/relayer/webhook'
      path: '/api/relayer/webhook'
      fullPath: '/api/relayer/webhook'
      preLoaderRoute: typeof ApiRelayerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor/register': {
      id: '/api/mentor/register'
      path: '/api/mentor/register'
      fullPath: '/api/mentor/register'
      preLoaderRoute: typeof ApiMentorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor/$walletAddress': {
      id: '/api/mentor/$walletAddress'
      path: '/api/mentor/$walletAddress'
      fullPath: '/api/mentor/$walletAddress'
      preLoaderRoute: typeof ApiMentorWalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor-by-username/$username': {
      id: '/api/mentor-by-username/$username'
      path: '/api/mentor-by-username/$username'
      fullPath: '/api/mentor-by-username/$username'
      preLoaderRoute: typeof ApiMentorByUsernameUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MUsernameRoute: MUsernameRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  MentorRegisterRoute: MentorRegisterRoute,
  MentorRegisteredRoute: MentorRegisteredRoute,
  ApiMentorByUsernameUsernameRoute: ApiMentorByUsernameUsernameRoute,
  ApiMentorWalletAddressRoute: ApiMentorWalletAddressRoute,
  ApiMentorRegisterRoute: ApiMentorRegisterRoute,
  ApiRelayerWebhookRoute: ApiRelayerWebhookRoute,
  ApiTransactionStatusRoute: ApiTransactionStatusRoute,
  MentorWalletAddressUpdateRoute: MentorWalletAddressUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
